### ISSUE TITLE
Small template issue (some color not customized)

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#337]
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/96581600-58633800-12da-11eb-8ef3-52fe38a7a34c.jpg)

![SharedScreenshot 1](https://user-images.githubusercontent.com/5006150/96581684-7b8de780-12da-11eb-9b23-e7e75a6a916d.jpg)

Maybe this two elements should respect the chooses branding color.

**Comment by PeopleInside** [comment]
It will be also nice if in the branding, broadcast message will be the possibility to decide the colour of the message banner.
Useful to put maybe red or other color that stay nice with the theme. Banner color and text color.

**Comment by PeopleInside** [comment]
I'm unable to use the following color: #1baed1 in branding, general because button loose his custom color.
![01](https://user-images.githubusercontent.com/5006150/96978274-77eaa280-151e-11eb-8989-26656a9638c0.jpg)
![02](https://user-images.githubusercontent.com/5006150/96978289-7ae59300-151e-11eb-85d5-bea2d4d3fac8.jpg)

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
Thanks for reporting, I am also able to reproduce this.

**Comment by PeopleInside** [comment]
Thank you, I will see ;-)

**Comment by PeopleInside** [comment]
Hi, I applied the patch but the look seems not to be very correct.
Look, folders are showed not in mine theme color:

![1](https://user-images.githubusercontent.com/5006150/117953684-8cee1e00-b316-11eb-846d-1a5c322a3fc8.jpg)

I reverted back my backup files.

How I expect is:

![2](https://user-images.githubusercontent.com/5006150/117955333-3bdf2980-b318-11eb-9465-fa4fc8df79d5.jpg)

**Comment by PeopleInside** [comment]
While checking for this issue I see an error repeated many time in console... maybe not related to the patch but still seems na issue of UVdesk

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/117958904-c83f1b80-b31b-11eb-8366-9be71f47a692.jpg)

**Comment by PeopleInside** [comment]
Seems you confused [my first screenshot](https://github.com/uvdesk/community-skeleton/issues/337#issuecomment-715203345)
Folder color was fine, the issue was in button color on top.

With this new patch you create issue also for folder color now.

**Comment by vipin-shrivastava** [comment]
@PeopleInside 

yes a bit confused with your first screenshot.

Now, I made some changes again, This is the file location, where you have to update the following files in your project:
**vendor/uvdesk/support-center-bundle/Resources/views/Knowledgebase**

1. Update "**darkSkin.html.twig**" from [here](https://github.com/vipin-shrivastava/support-center-bundle/blob/master/Resources/views/Knowledgebase/darkSkin.html.twig).

2. Update "**lightSkin.html.twig**" from [here](https://github.com/vipin-shrivastava/support-center-bundle/blob/master/Resources/views/Knowledgebase/lightSkin.html.twig).

After the updates in the following files. run the cache-clear command : php bin/console cache:clear
Now you can update the 'brandColor'. it should work now.

If these updates are creating the same issues, Please let me know.

**Comment by PeopleInside** [comment]
@vipin-shrivastava thank you, I will now check maybe will take some time.

Just a suggestion: be careful on changing the code just because users open issues.
I mean seems you changed the code without testing and seems something that works just fine was broken.

If I'm a not active user I can avoid to test the patch, issue is closed but is not solved is damaging other part of the code so I suggest to be more careful and test more changes.

I will try to see and update you in the next 5 days, if the issue will be resolved I will maybe closing the issue without adding more specific comments.

Thank you

**Comment by PeopleInside** [comment]
Seems work fine, thank you!
