### ISSUE TITLE
Error 500 when change customer avatar from operator side. Jquery updated 3.5.1

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#339]
- Create a customer profile as operator, activate and save it
- Upload now an avatar for the user and save

An error 500 is showed.

I'm testing UVdesk with JQuery updated.

Server error log, Apache, PHP 7.3

`[Fri Oct 23 12:25:30.145020 2020] [proxy_fcgi:error] [pid 2077753] [client ***] AH01071: Got error 'PHP message: PHP Fatal error:  require(): Failed opening required '/uvdesk/var/cache/prod/ContainerWozXxCm/removed-ids.php' (include_path='.:') in /uvdesk/var/cache/prod/ContainerWozXxCm/srcApp_KernelProdContainer.php on line 518', referer: https://helpdesk.peopleinside.it`

Not able to replicate in your online demo.

**Comment by PeopleInside** [comment]
Error 500 are generated also if a ticket is deleted (first deletion) than you open the ticket and three dots, delete).
If the customer has created for that ticket and is the only one ticket system will show numbers of ticket are negative (-1).

Step to reproduce:
- Open a ticket from a new customer, ticket generation should create the client
- Delete the ticket
- From deleted ticket open the ticket and on three dots menu delete it

I'm testing UVdesk with JQuery updated.
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/97114299-f0ed2400-16ef-11eb-8f3e-a27cf9555bcc.jpg)

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
I am not getting any issue while creating or uploading customer profile as an agent, please verify again if it's fixed now or still exist?

Regarding the ticket deletion from the trashed, I am also getting the error as shown below
![Screenshot_232](https://user-images.githubusercontent.com/43210406/105375321-a1ef5600-5c2e-11eb-865c-bb18469faf74.png)

**Comment by PeopleInside** [comment]
Great I cannot test now.
I also maybe I have not latest updated is past some time after your last update.
I keep always software updated but for sure your develop version has fix that I have not.

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul @PeopleInside 

>Regarding the ticket deletion from the trashed, I am also getting the error as shown below

We have fixed it [here](https://github.com/uvdesk/core-framework/commit/7f866a85b43c4847137e463b753068222667b5de) in master.

Locate path:
**vendor/uvdesk/core-framework/blob/master/Controller/Ticket.php**

Open your **Ticket.php** and replace its code from [here](https://github.com/uvdesk/core-framework/blob/master/Controller/Ticket.php).

**Comment by PeopleInside** [comment]
> 
> 
> @vaishaliwebkul @PeopleInside
> 
> > Regarding the ticket deletion from the trashed, I am also getting the error as shown below
> 
> We have fixed it [here](https://github.com/uvdesk/core-framework/commit/7f866a85b43c4847137e463b753068222667b5de) in master.
> 
> Locate path:
> **vendor/uvdesk/core-framework/blob/master/Controller/Ticket.php**
> 
> Open your **Ticket.php** and replace its code from [here](https://github.com/uvdesk/core-framework/blob/master/Controller/Ticket.php).

This patch create error 500 as soon I load operator ticket page.
Resumed my files.

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
I just pulled the core-framework but didn't get this issue https://prnt.sc/xvgu1p , could you please clear the project's cache or show the error.

**Comment by PeopleInside** [comment]
OK thanks I will try. I don't understand why GitHub doesn't allow to download a file directly u.u
This create issue replacing just one file or copy the content that maybe is not well copied.

**Comment by PeopleInside** [comment]
I still get 500 error when try to change user avatar profile.
You asked to check before and I was not able to do, I done it today and still 500 error if user avatar is changed by the operator.

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
I am not getting 500 error anymore while changing customer profile by operator end, you may check the attached video.
https://www.loom.com/share/9b1e5cb9c89348ca8f4e5834582b9d01

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> I am not getting 500 error anymore while changing customer profile by operator end, you may check the attached video.
> https://www.loom.com/share/9b1e5cb9c89348ca8f4e5834582b9d01

Ok maybe I need wait an updated version of uvdesk to test better. I get error 500.
I will wait to see maybe if future release fix issues. Is not easy for me patch every issue manually.

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
Okay! so currently I am closing this issue if this will still found in the next release then you are free to reopen this issue.

Thanks
